### ISSUE TITLE
Svelte plugin crashing

### ISSUE THREAD

**Issue by Jayphen** [coc-extensions/coc-svelte#13] opened 2020-08-28 14:27 UTC
To replicate, `npx degit "sveltejs/sapper-template#rollup" test`, open the `test` directory in vim and open a .svelte file.

You will see a notice `[coc.nvim] The "svelte" server crashed 5 times in the last 3 minutes.`.

I'm using the latest versions of both coc and coc-svelte. NVIM 0.4.4

**Comment by samrocksc** [comment] 2020-08-29 13:28
I duplicated this with the following settings:

NVIM: 0.5.0

**Comment by samrocksc** [comment] 2020-08-29 13:36
## Workaround 

If you go to the location of your plugin and `npm i -D typescript`, this issue is solved.

**Comment by benwoodward** [comment] 2020-08-31 10:10
Thanks @samrocksc, that worked for me: 

`cd ~/.config/coc/extensions/node_modules/coc-svelte`

**Comment by samrocksc** [comment] 2020-08-31 11:00
I'd PR a fix, but i'm still learning how to develop the plugins

**Comment by henryoliver** [comment] 2020-09-21 11:05
That solution solved the problem here as well:

```
cd ~/.config/coc/extensions/node_modules/coc-svelte
npm i -D typescript
```

Thanks

**Comment by jesperp** [comment] 2020-10-07 18:53
I think you can just install it through Plug like this instead:

`Plug 'coc-extensions/coc-svelte', {'do': 'yarn install --frozen-lockfile'}`

As explained in the _Note_ section here: https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension

**Comment by davidroeca** [comment] 2020-11-27 18:32
If this still doesn't work for you, try `Plug 'coc-extensions/coc-svelte', {'do': 'yarn install --frozen-lockfile && yarn build'}`

**Comment by davidroeca** [comment] 2020-12-01 05:39
I think this is a duplicate of https://github.com/coc-extensions/coc-svelte/issues/15. Should have been resolved by https://github.com/coc-extensions/coc-svelte/pull/18

**Closed by davidroeca** 2020-12-01 05:39 UTC
